import type { Game, PlayStatus } from '@gamepilot/types'

/**
 * Simple synthetic game library for persona stress-testing
 * Uses basic Game interface to avoid complex type issues
 */
export const mockLibraryGames: Game[] = [
  // Soulslike - High Difficulty, Single Player
  {
    id: 'dark-souls-remastered',
    title: 'Dark Souls Remastered',
    description: 'The acclaimed dark fantasy action RPG returns. Master brutal combat and intricate level design.',
    coverImage: 'https://cdn.cloudflare.steamstatic.com/steam/apps/570/header.jpg',
    releaseDate: new Date('2018-05-25'),
    developer: 'FromSoftware',
    publisher: 'Bandai Namco Entertainment',
    genres: [{ id: 'soulslike', name: 'Souls-like', description: 'Challenging action RPGs', icon: '⚔️', color: 'red', tags: ['challenging', 'dark'] }, { id: 'dark-fantasy', name: 'Dark Fantasy', description: 'Dark fantasy settings', icon: '🌙', color: 'purple', tags: ['dark', 'fantasy'] }] as any,
    moods: ['challenging', 'dark'] as any,
    platforms: [{ id: 'steam', name: 'Steam', code: 'steam' as any, isConnected: true }],
    emotionalTags: ['Competitive', 'Challenging'] as any,
    playStatus: 'completed' as PlayStatus,
    hoursPlayed: 127,
    lastPlayed: new Date('2024-01-15'),
    addedAt: new Date('2023-06-10'),
    isFavorite: true,
    releaseYear: 2018,
    achievements: { unlocked: 42, total: 43 },
  },

  // Roguelike - High Difficulty, Single Player
  {
    id: 'hades',
    title: 'Hades',
    description: 'Defy the god of the dead as you hack and slash out of the Underworld in this rogue-like dungeon crawler.',
    coverImage: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1145400/header.jpg',
    releaseDate: new Date('2020-09-17'),
    developer: 'Supergiant Games',
    publisher: 'Supergiant Games',
    genres: ['indie', 'humorous'] as any,
    moods: ['creative', 'humorous'] as any,
    platforms: [{ id: 'steam', name: 'Steam', code: 'steam' as any, isConnected: true }],
    emotionalTags: ['Chill', 'Creative'] as any,
    playStatus: 'playing' as PlayStatus,
    hoursPlayed: 89,
    lastPlayed: new Date('2024-01-20'),
    addedAt: new Date('2023-08-15'),
    isFavorite: true,
    releaseYear: 2020,
    achievements: { unlocked: 38, total: 50 }
  },

  // Casual Puzzle - Low Difficulty, Single Player
  {
    id: 'portal-2',
    title: 'Portal 2',
    description: 'The highly anticipated sequel to 2007\'s Game of the Year, Portal 2 is a hilariously mind-bending adventure.',
    coverImage: 'https://cdn.cloudflare.steamstatic.com/steam/apps/620/header.jpg',
    releaseDate: new Date('2011-04-19'),
    developer: 'Valve',
    publisher: 'Valve',
    genres: ['physics-puzzle', 'comedy'] as any,
    moods: ['relaxed', 'humorous'] as any,
    platforms: [{ id: 'steam', name: 'Steam', code: 'steam' as any, isConnected: true }],
    emotionalTags: ['clever', 'funny'] as any,
    playStatus: 'completed' as PlayStatus,
    hoursPlayed: 12,
    lastPlayed: new Date('2023-12-01'),
    addedAt: new Date('2023-05-20'),
    isFavorite: false,
    releaseYear: 2011,
    achievements: { unlocked: 50, total: 50 }
  },

  // MMO - Multiplayer, Medium Difficulty
  {
    id: 'final-fantasy-xiv',
    title: 'Final Fantasy XIV Online',
    description: 'Take part in an epic and ever-changing FINAL FANTASY as you adventure and explore with friends.',
    coverImage: 'https://cdn.cloudflare.steamstatic.com/steam/apps/39210/header.jpg',
    releaseDate: new Date('2013-08-27'),
    developer: 'Square Enix',
    publisher: 'Square Enix',
    genres: ['fantasy', 'online-multiplayer'] as any,
    moods: ['strategic', 'social'] as any,
    platforms: [{ id: 'steam', name: 'Steam', code: 'steam' as any, isConnected: true }],
    emotionalTags: ['social', 'epic'] as any,
    playStatus: 'playing' as PlayStatus,
    hoursPlayed: 456,
    lastPlayed: new Date('2024-01-21'),
    addedAt: new Date('2022-03-15'),
    isFavorite: true,
    releaseYear: 2013,
    achievements: { unlocked: 245, total: 500 }
  },

  // Competitive FPS - High Difficulty, Multiplayer
  {
    id: 'counter-strike-2',
    title: 'Counter-Strike 2',
    description: 'Counter-Strike 2 is a free upgrade to CS:GO, building on the tactical foundation.',
    coverImage: 'https://cdn.cloudflare.steamstatic.com/steam/apps/730/header.jpg',
    releaseDate: new Date('2023-09-27'),
    developer: 'Valve',
    publisher: 'Valve',
    genres: ['tactical-shooter', 'multiplayer'] as any,
    moods: ['competitive', 'intense'] as any,
    platforms: [{ id: 'steam', name: 'Steam', code: 'steam' as any, isConnected: true }],
    emotionalTags: ['competitive', 'intense'] as any,
    playStatus: 'playing' as PlayStatus,
    hoursPlayed: 234,
    lastPlayed: new Date('2024-01-21'),
    addedAt: new Date('2023-10-01'),
    isFavorite: false,
    releaseYear: 2023,
    achievements: { unlocked: 15, total: 30 }
  },

  // Co-op Adventure - Medium Difficulty
  {
    id: 'it-takes-two',
    title: 'It Takes Two',
    description: 'Embark on the craziest journey of your life in It Takes Two, a genre-bending platform adventure.',
    coverImage: 'https://via.placeholder.com/300x400/FF69B4/FFFFFF?text=It+Takes+Two',
    releaseDate: new Date('2021-03-26'),
    developer: 'Hazelight Studios',
    publisher: 'Electronic Arts',
    genres: ['co-op', 'comedy'] as any,
    moods: ['social', 'humorous'] as any,
    platforms: [{ id: 'steam', name: 'Steam', code: 'steam' as any, isConnected: true }],
    emotionalTags: ['fun', 'cooperative'] as any,
    playStatus: 'completed' as PlayStatus,
    hoursPlayed: 14,
    lastPlayed: new Date('2023-11-15'),
    addedAt: new Date('2023-09-01'),
    isFavorite: true,
    releaseYear: 2021,
    achievements: { unlocked: 35, total: 35 }
  },

  // Strategy Game - High Difficulty, Single Player
  {
    id: 'civilization-vi',
    title: 'Civilization VI',
    description: 'Build an empire to stand the test of time in this turn-based strategy classic.',
    coverImage: 'https://via.placeholder.com/300x400/8B4513/FFFFFF?text=Civ+VI',
    releaseDate: new Date('2016-10-21'),
    developer: 'Firaxis Games',
    publisher: '2K Games',
    genres: ['4x', 'historical'] as any,
    moods: ['strategic', 'focused'] as any,
    platforms: [{ id: 'steam', name: 'Steam', code: 'steam' as any, isConnected: true }],
    emotionalTags: ['strategic', 'addictive'] as any,
    playStatus: 'playing' as PlayStatus,
    hoursPlayed: 189,
    lastPlayed: new Date('2024-01-19'),
    addedAt: new Date('2022-01-10'),
    isFavorite: false,
    releaseYear: 2016,
    achievements: { unlocked: 89, total: 150 }
  },

  // RPG - Medium Difficulty, Single Player
  {
    id: 'the-witcher-3',
    title: 'The Witcher 3: Wild Hunt',
    description: 'You are Geralt of Rivia, mercenary monster slayer. Before you stands a war-torn world.',
    coverImage: 'https://cdn.cloudflare.steamstatic.com/steam/apps/292030/header.jpg',
    releaseDate: new Date('2015-05-19'),
    developer: 'CD Projekt Red',
    publisher: 'CD Projekt Red',
    genres: ['fantasy', 'story-rich'] as any,
    moods: ['epic', 'immersive'] as any,
    platforms: [{ id: 'steam', name: 'Steam', code: 'steam' as any, isConnected: true }],
    emotionalTags: ['epic', 'story-driven'] as any,
    playStatus: 'completed' as PlayStatus,
    hoursPlayed: 156,
    lastPlayed: new Date('2023-10-20'),
    addedAt: new Date('2022-06-15'),
    isFavorite: true,
    releaseYear: 2015,
    achievements: { unlocked: 67, total: 78 }
  },

  // Casual Simulation - Low Difficulty
  {
    id: 'stardew-valley',
    title: 'Stardew Valley',
    description: 'You\'ve inherited your grandfather\'s old farm plot in Stardew Valley. Armed with hand-me-down tools.',
    coverImage: 'https://cdn.cloudflare.steamstatic.com/steam/apps/413150/header.jpg',
    releaseDate: new Date('2016-02-26'),
    developer: 'ConcernedApe',
    publisher: 'ConcernedApe',
    genres: ['farming', 'relaxing'] as any,
    moods: ['relaxed', 'peaceful'] as any,
    platforms: [{ id: 'steam', name: 'Steam', code: 'steam' as any, isConnected: true }],
    emotionalTags: ['relaxing', 'charming'] as any,
    playStatus: 'playing' as PlayStatus,
    hoursPlayed: 78,
    lastPlayed: new Date('2024-01-20'),
    addedAt: new Date('2023-07-20'),
    isFavorite: true,
    releaseYear: 2016,
    achievements: { unlocked: 23, total: 40 }
  },

  // Horror - High Difficulty, Single Player
  {
    id: 'resident-evil-8',
    title: 'Resident Evil 8 Village',
    description: 'Experience survival horror like never before in the eighth major installment.',
    coverImage: 'https://via.placeholder.com/300x400/000000/FFFFFF?text=RE8',
    releaseDate: new Date('2021-05-07'),
    developer: 'Capcom',
    publisher: 'Capcom',
    genres: ['third-person-shooter', 'zombies'] as any,
    moods: ['intense', 'scary'] as any,
    platforms: [{ id: 'steam', name: 'Steam', code: 'steam' as any, isConnected: true }],
    emotionalTags: ['scary', 'intense'] as any,
    playStatus: 'paused' as PlayStatus,
    hoursPlayed: 8,
    lastPlayed: new Date('2024-01-10'),
    addedAt: new Date('2023-11-01'),
    isFavorite: false,
    releaseYear: 2021,
    achievements: { unlocked: 12, total: 30 }
  },

  // Racing - Medium Difficulty
  {
    id: 'forza-horizon-5',
    title: 'Forza Horizon 5',
    description: 'Your Ultimate Horizon Adventure awaits! Explore the vibrant open world of Mexico.',
    coverImage: 'https://via.placeholder.com/300x400/FF4500/FFFFFF?text=Forza+5',
    releaseDate: new Date('2021-11-09'),
    developer: 'Playground Games',
    publisher: 'Xbox Game Studios',
    genres: ['arcade-racing', 'multiplayer'] as any,
    moods: ['exciting', 'beautiful'] as any,
    platforms: [{ id: 'steam', name: 'Steam', code: 'steam' as any, isConnected: true }],
    emotionalTags: ['exciting', 'beautiful'] as any,
    playStatus: 'playing' as PlayStatus,
    hoursPlayed: 45,
    lastPlayed: new Date('2024-01-18'),
    addedAt: new Date('2023-12-15'),
    isFavorite: false,
    releaseYear: 2021,
    achievements: { unlocked: 56, total: 100 }
  },

  // Indie Platformer - Medium Difficulty
  {
    id: 'celeste',
    title: 'Celeste',
    description: 'Help Madeline survive her inner demons on her journey to the top of Celeste Mountain.',
    coverImage: 'https://via.placeholder.com/300x400/FFB6C1/FFFFFF?text=Celeste',
    releaseDate: new Date('2018-01-25'),
    developer: 'Maddy Makes Games',
    publisher: 'Maddy Makes Games',
    genres: ['precision-platformer', 'story-rich'] as any,
    moods: ['focused', 'strategic'] as any,
    platforms: [{ id: 'steam', name: 'Steam', code: 'steam' as any, isConnected: true }],
    emotionalTags: ['challenging', 'emotional'] as any,
    playStatus: 'completed' as PlayStatus,
    hoursPlayed: 23,
    lastPlayed: new Date('2023-09-10'),
    addedAt: new Date('2023-05-25'),
    isFavorite: true,
    releaseYear: 2018,
    achievements: { unlocked: 25, total: 25 }
  },

  // Battle Royale - Multiplayer
  {
    id: 'apex-legends',
    title: 'Apex Legends',
    description: 'Conquer with character in Apex Legends, a free-to-play hero shooter.',
    coverImage: 'https://via.placeholder.com/300x400/FF0000/FFFFFF?text=Apex+Legends',
    releaseDate: new Date('2019-02-04'),
    developer: 'Respawn Entertainment',
    publisher: 'Electronic Arts',
    genres: ['hero-shooter', 'multiplayer'] as any,
    moods: ['competitive', 'intense'] as any,
    platforms: [{ id: 'steam', name: 'Steam', code: 'steam' as any, isConnected: true }],
    emotionalTags: ['competitive', 'fast-paced'] as any,
    playStatus: 'playing' as PlayStatus,
    hoursPlayed: 167,
    lastPlayed: new Date('2024-01-21'),
    addedAt: new Date('2022-02-14'),
    isFavorite: false,
    releaseYear: 2019,
    achievements: { unlocked: 45, total: 100 }
  },

  // City Builder - Medium Difficulty
  {
    id: 'cities-skylines',
    title: 'Cities: Skylines',
    description: 'Cities: Skylines is a modern take on the classic city simulation.',
    coverImage: 'https://via.placeholder.com/300x400/4169E1/FFFFFF?text=Cities+Skylines',
    releaseDate: new Date('2015-03-10'),
    developer: 'Colossal Order',
    publisher: 'Paradox Interactive',
    genres: ['city-builder', 'management'] as any,
    moods: ['creative', 'relaxing'] as any,
    platforms: [{ id: 'steam', name: 'Steam', code: 'steam' as any, isConnected: true }],
    emotionalTags: ['creative', 'relaxing'] as any,
    playStatus: 'playing' as PlayStatus,
    hoursPlayed: 98,
    lastPlayed: new Date('2024-01-17'),
    addedAt: new Date('2022-08-20'),
    isFavorite: false,
    releaseYear: 2015,
    achievements: { unlocked: 34, total: 50 }
  },

  // Action RPG - Medium Difficulty
  {
    id: 'diablo-4',
    title: 'Diablo IV',
    description: 'The legendary RPG returns. Darkness returns to Sanctuary.',
    coverImage: 'https://via.placeholder.com/300x400/8B0000/FFFFFF?text=Diablo+4',
    releaseDate: new Date('2023-06-06'),
    developer: 'Blizzard Entertainment',
    publisher: 'Blizzard Entertainment',
    genres: ['dungeon-crawler', 'dark-fantasy'] as any,
    moods: ['strategic', 'mysterious'] as any,
    platforms: [{ id: 'steam', name: 'Steam', code: 'steam' as any, isConnected: true }],
    emotionalTags: ['intense', 'dark'] as any,
    playStatus: 'playing' as PlayStatus,
    hoursPlayed: 67,
    lastPlayed: new Date('2024-01-21'),
    addedAt: new Date('2023-06-10'),
    isFavorite: true,
    releaseYear: 2023,
    achievements: { unlocked: 28, total: 50 }
  },

  // Sports - Low Difficulty
  {
    id: 'fifa-24',
    title: 'EA Sports FC 24',
    description: 'EA Sports FC 24 brings you the world of football with over 19,000 players.',
    coverImage: 'https://via.placeholder.com/300x400/00FF00/FFFFFF?text=FC+24',
    releaseDate: new Date('2023-09-29'),
    developer: 'EA Vancouver',
    publisher: 'EA Sports',
    genres: ['football', 'multiplayer'] as any,
    moods: ['competitive', 'energetic'] as any,
    platforms: [{ id: 'steam', name: 'Steam', code: 'steam' as any, isConnected: true }],
    emotionalTags: ['competitive', 'realistic'] as any,
    playStatus: 'playing' as PlayStatus,
    hoursPlayed: 34,
    lastPlayed: new Date('2024-01-20'),
    addedAt: new Date('2023-10-15'),
    isFavorite: false,
    releaseYear: 2023,
    achievements: { unlocked: 12, total: 30 }
  },

  // Survival Craft - Medium Difficulty
  {
    id: 'minecraft',
    title: 'Minecraft',
    description: 'Explore infinite worlds and build everything from the simplest of homes to the grandest of castles.',
    coverImage: 'https://via.placeholder.com/300x400/8B4513/FFFFFF?text=Minecraft',
    releaseDate: new Date('2011-11-18'),
    developer: 'Mojang Studios',
    publisher: 'Mojang Studios',
    genres: ['crafting', 'creative'] as any,
    moods: ['creative', 'relaxed'] as any,
    platforms: [{ id: 'steam', name: 'Steam', code: 'steam' as any, isConnected: true }],
    emotionalTags: ['creative', 'relaxing'] as any,
    playStatus: 'playing' as PlayStatus,
    hoursPlayed: 234,
    lastPlayed: new Date('2024-01-19'),
    addedAt: new Date('2021-03-10'),
    isFavorite: true,
    releaseYear: 2011,
    achievements: { unlocked: 45, total: 100 }
  },

  // Stealth - Medium Difficulty
  {
    id: 'metal-gear-solid-v',
    title: 'Metal Gear Solid V: The Phantom Pain',
    description: 'Ushering in a new era for the franchise with cutting-edge technology powered by Fox Engine.',
    coverImage: 'https://via.placeholder.com/300x400/000080/FFFFFF?text=MGSV',
    releaseDate: new Date('2015-09-01'),
    developer: 'Kojima Productions',
    publisher: 'Konami',
    genres: ['tactical', 'open-world'] as any,
    moods: ['strategic', 'exploratory'] as any,
    platforms: [{ id: 'steam', name: 'Steam', code: 'steam' as any, isConnected: true }],
    emotionalTags: ['strategic', 'cinematic'] as any,
    playStatus: 'unplayed' as PlayStatus,
    hoursPlayed: 0,
    lastPlayed: undefined,
    addedAt: new Date('2023-12-01'),
    isFavorite: false,
    releaseYear: 2015,
    achievements: { unlocked: 0, total: 50 }
  },

  // Fighting Game - High Difficulty
  {
    id: 'street-fighter-6',
    title: 'Street Fighter 6',
    description: 'Street Fighter 6 features groundbreaking crossplay technology.',
    coverImage: 'https://via.placeholder.com/300x400/FFD700/FFFFFF?text=SF6',
    releaseDate: new Date('2023-06-02'),
    developer: 'Capcom',
    publisher: 'Capcom',
    genres: ['arcade', 'multiplayer'] as any,
    moods: ['competitive', 'lighthearted'] as any,
    platforms: [{ id: 'steam', name: 'Steam', code: 'steam' as any, isConnected: true }],
    emotionalTags: ['competitive', 'fast-paced'] as any,
    playStatus: 'playing' as PlayStatus,
    hoursPlayed: 56,
    lastPlayed: new Date('2024-01-21'),
    addedAt: new Date('2023-06-05'),
    isFavorite: false,
    releaseYear: 2023,
    achievements: { unlocked: 23, total: 40 }
  },

  // Visual Novel - Low Difficulty
  {
    id: 'life-is-strange',
    title: 'Life is Strange',
    description: 'Experience a bold new era in interactive entertainment with Life is Strange.',
    coverImage: 'https://via.placeholder.com/300x400/87CEEB/FFFFFF?text=Life+is+Strange',
    releaseDate: new Date('2015-01-30'),
    developer: 'Dontnod Entertainment',
    publisher: 'Square Enix',
    genres: ['story-rich', 'choice-driven'] as any,
    moods: ['immersive', 'thoughtful'] as any,
    platforms: [{ id: 'steam', name: 'Steam', code: 'steam' as any, isConnected: true }],
    emotionalTags: ['emotional', 'story-driven'] as any,
    playStatus: 'completed' as PlayStatus,
    hoursPlayed: 18,
    lastPlayed: new Date('2023-08-15'),
    addedAt: new Date('2023-04-10'),
    isFavorite: true,
    releaseYear: 2015,
    achievements: { unlocked: 30, total: 30 }
  },

  // Tower Defense - Medium Difficulty
  {
    id: 'bloons-td-6',
    title: 'Bloons TD 6',
    description: 'The Bloons are back and better than ever! Get ready for a massive 3D tower defense game.',
    coverImage: 'https://via.placeholder.com/300x400/FF69B4/FFFFFF?text=BTD6',
    releaseDate: new Date('2018-12-18'),
    developer: 'Ninja Kiwi',
    publisher: 'Ninja Kiwi',
    genres: ['casual', 'colorful'] as any,
    moods: ['relaxed', 'creative'] as any,
    platforms: [{ id: 'steam', name: 'Steam', code: 'steam' as any, isConnected: true }],
    emotionalTags: ['addictive', 'colorful'] as any,
    playStatus: 'playing' as PlayStatus,
    hoursPlayed: 89,
    lastPlayed: new Date('2024-01-21'),
    addedAt: new Date('2022-11-20'),
    isFavorite: false,
    releaseYear: 2018,
    achievements: { unlocked: 67, total: 100 }
  },

  // Card Game - Medium Difficulty
  {
    id: 'hearthstone',
    title: 'Hearthstone',
    description: 'Hearthstone is a digital collectible card game set in the Warcraft universe.',
    coverImage: 'https://via.placeholder.com/300x400/FFD700/FFFFFF?text=Hearthstone',
    releaseDate: new Date('2014-03-11'),
    developer: 'Blizzard Entertainment',
    publisher: 'Blizzard Entertainment',
    genres: ['digital-card-game', 'multiplayer'] as any,
    moods: ['strategic', 'competitive'] as any,
    platforms: [{ id: 'steam', name: 'Steam', code: 'steam' as any, isConnected: true }],
    emotionalTags: ['strategic', 'addictive'] as any,
    playStatus: 'paused' as PlayStatus,
    hoursPlayed: 145,
    lastPlayed: new Date('2023-12-15'),
    addedAt: new Date('2021-06-15'),
    isFavorite: false,
    releaseYear: 2014,
    achievements: { unlocked: 89, total: 150 }
  },

  // Puzzle Platformer - Medium Difficulty
  {
    id: 'hollow-knight',
    title: 'Hollow Knight',
    description: 'Forge your own path in Hollow Knight! An epic action adventure through a ruined kingdom.',
    coverImage: 'https://via.placeholder.com/300x400/4B0082/FFFFFF?text=Hollow+Knight',
    releaseDate: new Date('2017-02-24'),
    developer: 'Team Cherry',
    publisher: 'Team Cherry',
    genres: ['indie', 'challenging'] as any,
    moods: ['challenging', 'beautiful'] as any,
    platforms: [{ id: 'steam', name: 'Steam', code: 'steam' as any, isConnected: true }],
    emotionalTags: ['challenging', 'beautiful'] as any,
    playStatus: 'completed' as PlayStatus,
    hoursPlayed: 67,
    lastPlayed: new Date('2023-10-05'),
    addedAt: new Date('2023-02-15'),
    isFavorite: true,
    releaseYear: 2017,
    achievements: { unlocked: 56, total: 112 }
  },

  // Management Sim - Medium Difficulty
  {
    id: 'two-point-hospital',
    title: 'Two Point Hospital',
    description: 'Design and build your own hospital in this management sim.',
    coverImage: 'https://via.placeholder.com/300x400/00CED1/FFFFFF?text=Two+Point+Hospital',
    releaseDate: new Date('2018-08-30'),
    developer: 'Two Point Studios',
    publisher: 'Sega',
    genres: ['hospital-sim', 'humorous'] as any,
    moods: ['relaxed', 'humorous'] as any,
    platforms: [{ id: 'steam', name: 'Steam', code: 'steam' as any, isConnected: true }],
    emotionalTags: ['humorous', 'addictive'] as any,
    playStatus: 'playing' as PlayStatus,
    hoursPlayed: 34,
    lastPlayed: new Date('2024-01-18'),
    addedAt: new Date('2023-09-20'),
    isFavorite: false,
    releaseYear: 2018,
    achievements: { unlocked: 23, total: 50 }
  }
]
